const Data = [
  {
    name: 'HTML / CSS',
    calcFlag: false,
    year: 3,
    startDate: null,
    icon: 'devicon-html5-plain-wordmark colored',
    type: 'language',
    month: null,
  },
  {
    name: 'jQuery',
    calcFlag: false,
    year: 3,
    startDate: null,
    icon: 'devicon-jquery-plain-wordmark colored',
    type: 'language',
    month: null,
  },
  {
    name: 'PHP',
    calcFlag: false,
    year: 3,
    startDate: null,
    icon: 'devicon-php-plain colored',
    type: 'language',
    month: null,
  },
  {
    name: 'Scss',
    calcFlag: false,
    year: 3,
    startDate: null,
    icon: 'devicon-sass-original colored',
    type: 'language',
    month: null,
  },
  {
    name: 'TypeScript',
    calcFlag: true,
    year: null,
    startDate: null,
    icon: 'devicon-typescript-plain colored',
    type: 'language',
    month: 3,
  },

  {
    name: 'WordPress',
    calcFlag: false,
    year: 3,
    startDate: null,
    icon: 'devicon-wordpress-plain',
    type: 'framework',
    month: null,
  },
  {
    name: 'React',
    calcFlag: true,
    year: null,
    startDate: null,
    icon: 'devicon-react-original colored',
    type: 'framework',
    month: 3,
  },
  {
    name: 'Three.js',
    calcFlag: true,
    year: null,
    startDate: null,
    icon: 'devicon-threejs-original',
    type: 'framework',
    month: 4,
  },

  {
    name: 'Git',
    calcFlag: false,
    year: 3,
    startDate: null,
    icon: 'devicon-git-plain colored',
    type: 'others',
    month: null,
  },
  {
    name: 'VSCode',
    calcFlag: false,
    year: 3,
    startDate: null,
    icon: 'devicon-vscode-plain colored',
    type: 'others',
    month: null,
  },
  {
    name: 'Blender',
    calcFlag: true,
    year: null,
    startDate: null,
    icon: 'devicon-blender-original colored',
    type: 'others',
    month: 4,
  },
]

export default Data